on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: moergo-sc/zmk/.github/workflows/build-user-config.yml@ce69e85f585c724142aae37ddf8a7e019ff19e93 # MoErgo v26.09; matches firmware/Zephyr
